name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image for Testing
        run: docker build -t myimage:test .
      - name: Run Tests
        run: |
          # Run a simple test, for example, checking Python version.
          docker run --rm myimage:test python --version

  build:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker Image
        run: docker build -t mydockerhubusername/myimage:latest .
      - name: Push the Docker Image
        run: docker push mydockerhubusername/myimage:latest
